const {request}=require('../../utils/request');const {ensureLogin}=require('../../utils/auth');const docs=require('../../utils/enterprise-documents');
Page({data:{certificationType:'COMPANY',types:['企业','机构','毕业院校'],applicationNote:'',record:null,companyName:'',creditCode:'',evidence:[],busy:false,uploading:false,ready:false,error:'',editable:false},
 onShow(){const u=ensureLogin();if(!u)return;if(u.role!=='ENGINEER'){wx.showToast({title:'仅工程师可申请',icon:'none'});return;}if(!this.data.ready)this.load();},
 onPullDownRefresh(){if(this.data.editable||this.data.uploading||this.data.busy){wx.stopPullDownRefresh();return;}this.load().finally(()=>wx.stopPullDownRefresh());},
 async load(){try{const r=await request('GET','/enterprise');this.setData({record:r?{...r,statusText:({PENDING:'审核中',APPROVED:'认证已通过',REJECTED:'未通过，请修改后重新提交'})[r.status]}:null,certificationType:r?.certificationType||'COMPANY',applicationNote:r?.applicationNote||'',companyName:r?.companyName||'',creditCode:r?.creditCode||'',evidence:r?.evidence||[],editable:!r||r.status==='REJECTED',ready:true,error:''});}catch(e){this.setData({error:e.message,ready:false});}},
 chooseType(e){this.setData({certificationType:['COMPANY','INSTITUTION','SCHOOL'][Number(e.detail.value)],creditCode:''});},
 input(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},
 async add(){if(this.data.uploading||this.data.busy||this.data.evidence.length>=5)return;this.setData({uploading:true});try{const chosen=await new Promise((resolve,reject)=>wx.chooseImage({count:5-this.data.evidence.length,sizeType:['compressed'],success:resolve,fail:reject}));for(const path of chosen.tempFilePaths){const r=await docs.upload(path);this.setData({evidence:this.data.evidence.concat(r.id)});}}catch(e){if(!String(e.errMsg||'').includes('cancel'))wx.showToast({title:e.message||'上传失败',icon:'none'});}finally{this.setData({uploading:false});}},
 remove(e){if(!this.data.busy&&!this.data.uploading)this.setData({evidence:this.data.evidence.filter(x=>x!==e.currentTarget.dataset.id)});},preview(e){docs.preview(e.currentTarget.dataset.id);},
 async submit(){if(this.data.busy||this.data.uploading||!this.data.editable)return;this.setData({busy:true});try{await request('POST','/enterprise',{certificationType:this.data.certificationType,applicationNote:this.data.applicationNote,companyName:this.data.companyName,creditCode:this.data.creditCode,evidence:this.data.evidence});wx.showToast({title:'已提交审核'});await this.load();}catch(e){wx.showToast({title:e.message,icon:'none'});}finally{this.setData({busy:false});}}
});
