const {request}=require('../../../utils/request');const {loadAdmin,hasPermission,denyAndExit}=require('../../utils/admin');
function parts(value){const s=new Date(new Date(value).getTime()+8*3600000).toISOString();return {date:s.slice(0,10),time:s.slice(11,16)};}
Page({data:{items:[],form:null,roles:['全部角色','客户','工程师'],roleKeys:['ALL','CUSTOMER','ENGINEER'],offset:0,hasMore:false,busy:false,error:''},async onLoad(){try{const a=await loadAdmin();if(!hasPermission(a,'ANNOUNCEMENT_MANAGE'))throw Error('没有公告管理权限');this._ready=true;this.load();}catch(e){denyAndExit(e.message);}},onPullDownRefresh(){this.load().finally(()=>wx.stopPullDownRefresh());},
 async load(more=false){if(!this._ready)return;try{const offset=more===true?this.data.offset:0,r=await request('GET','/admin/announcements',{offset});const now=Date.now();const items=r.items.map(x=>({...x,displayState:!x.enabled?'已下线':new Date(x.endsAt)<=now?'已结束':new Date(x.startsAt)>now?'待开始':'展示中',roleText:({ALL:'全部角色',CUSTOMER:'客户',ENGINEER:'工程师'})[x.targetRole]}));this.setData({items:more===true?this.data.items.concat(items):items,offset:offset+20,hasMore:r.hasMore,error:''});}catch(e){this.setData({error:e.message});}},more(){this.load(true);},
 add(){const start=parts(Date.now()),end=parts(Date.now()+86400000);this.setData({form:{title:'',content:'',roleIndex:0,enabled:true,startDate:start.date,startTime:start.time,endDate:end.date,endTime:end.time}});},
 edit(e){const a=this.data.items.find(x=>x.id===e.currentTarget.dataset.id),start=parts(a.startsAt),end=parts(a.endsAt);this.setData({form:{...a,enabled:!!a.enabled,roleIndex:this.data.roleKeys.indexOf(a.targetRole),startDate:start.date,startTime:start.time,endDate:end.date,endTime:end.time}});},
 input(e){this.setData({['form.'+e.currentTarget.dataset.key]:e.detail.value});},role(e){this.setData({'form.roleIndex':Number(e.detail.value)});},toggle(e){this.setData({'form.enabled':e.detail.value});},cancel(){this.setData({form:null});},
 async save(){if(this.data.busy)return;this.setData({busy:true});try{const f=this.data.form;await request('POST','/admin/announcements',{id:f.id,revision:f.revision,title:f.title,content:f.content,targetRole:this.data.roleKeys[f.roleIndex],enabled:f.enabled,startsAt:f.startDate+'T'+f.startTime+':00+08:00',endsAt:f.endDate+'T'+f.endTime+':00+08:00'});this.setData({form:null});await this.load();wx.showToast({title:'公告已保存'});}catch(e){wx.showToast({title:e.message,icon:'none'});}finally{this.setData({busy:false});}}
});
