const {request}=require('../../utils/request');
const labels={OPEN:'待回应',PROCESSING:'处理中',RESOLVED:'已处理',CLOSED:'已关闭'};
Component({properties:{admin:Boolean},data:{items:[],detail:null,form:false,title:'',content:'',category:'账号异常',categories:['账号异常','订单/交易','纠纷售后','发票问题','其他'],reply:'',evidence:[],faq:[],busy:false,error:'',offset:0,hasMore:false},lifetimes:{attached(){this.start();},detached(){this.stop();}},pageLifetimes:{show(){this.start();},hide(){this.stop();}},methods:{
 base(){return (this.data.admin?'/admin':'')+'/service-tickets';},start(){if(this._active)return;this._active=true;this.load();if(!this.data.admin)request('GET','/help',null,{silent:true}).then(faq=>{if(this._active)this.setData({faq:faq.filter(x=>x.kind==='FAQ')});}).catch(()=>{});this._poll=setInterval(()=>{if(this.data.detail)this.openId(this.data.detail.id);},15000);},stop(){this._active=false;this._detailVersion=(this._detailVersion||0)+1;clearInterval(this._poll);},
 async load(more=false){try{const offset=more===true?this.data.offset:0,r=await request('GET',this.base(),{offset});if(!this._active)return;const items=r.items.map(x=>({...x,statusText:labels[x.status]}));this.setData({items:more===true?this.data.items.concat(items):items,offset:offset+20,hasMore:r.hasMore,error:''});}catch(e){if(this._active)this.setData({error:e.message});}},more(){this.load(true);},
 create(){this._detailVersion=(this._detailVersion||0)+1;this.setData({form:true,detail:null});},cancel(){this.setData({form:false});},input(e){this.setData({[e.currentTarget.dataset.key]:e.detail.value});},category(e){this.setData({category:this.data.categories[Number(e.detail.value)]});},
 async addImage(){if(this.data.busy||this.data.evidence.length>=5)return;this.setData({busy:true});try{const image=await new Promise((resolve,reject)=>wx.chooseImage({count:1,sizeType:['compressed'],success:resolve,fail:reject}));const c=await new Promise((resolve,reject)=>wx.compressImage({src:image.tempFilePaths[0],quality:30,compressedWidth:1200,success:resolve,fail:reject}));const f=await new Promise((resolve,reject)=>wx.getFileSystemManager().readFile({filePath:c.tempFilePath,encoding:'base64',success:resolve,fail:reject}));if(f.data.length>546136)throw Error('截图过大，请裁剪后重试');const r=await request('POST','/support/evidence',{base64:f.data});this.setData({evidence:this.data.evidence.concat(r.id)});}catch(e){if(!String(e.errMsg||'').includes('cancel'))wx.showToast({title:e.message||'上传失败',icon:'none'});}finally{this.setData({busy:false});}},remove(e){if(!this.data.busy)this.setData({evidence:this.data.evidence.filter(x=>x!==e.currentTarget.dataset.id)});},
 async submit(){if(this.data.busy)return;this.setData({busy:true});try{const r=await request('POST',this.base(),{category:this.data.category,title:this.data.title,content:this.data.content,evidence:this.data.evidence});this.setData({form:false,title:'',content:'',evidence:[]});await this.load();await this.openId(r.id);}catch(e){wx.showToast({title:e.message,icon:'none'});}finally{this.setData({busy:false});}},
 open(e){this.openId(e.currentTarget.dataset.id);},async openId(id){const version=this._detailVersion=(this._detailVersion||0)+1;try{const r=await request('GET',this.base()+'/'+id,null,{silent:true});if(this._active&&version===this._detailVersion)this.setData({detail:{...r,statusText:labels[r.status]},error:''});}catch(e){if(this._active)this.setData({error:e.message});}},back(){this._detailVersion=(this._detailVersion||0)+1;this.setData({detail:null,reply:''});this.load();},
 async action(e){if(this.data.busy)return;const action=e.currentTarget.dataset.action;this.setData({busy:true});try{await request('POST',this.base()+'/'+this.data.detail.id,{action,content:this.data.reply});this.setData({reply:''});await this.openId(this.data.detail.id);}catch(e){wx.showToast({title:e.message,icon:'none'});}finally{this.setData({busy:false});}},
 preview(e){require('../../utils/community').previewEvidence(e.currentTarget.dataset.id,this.data.admin);},faq(e){const f=this.data.faq.find(x=>x.id===e.currentTarget.dataset.id);if(f)wx.showModal({title:f.title,content:f.content,showCancel:false});}
}});
