const {request}=require('../../utils/request');
Component({data:{current:null},lifetimes:{attached(){this.start();},detached(){this.stop();}},pageLifetimes:{show(){this.start();},hide(){this.stop();}},methods:{
 start(){if(this._active)return;this._active=true;this._items=[];this.setData({current:null});this.load();this._timer=setInterval(()=>this.load(),60000);this._expiry=setInterval(()=>{if(this.data.current&&new Date(this.data.current.endsAt).getTime()<=Date.now()+(this._offset||0))this.next();},1000);},
 stop(){this._active=false;this._version=(this._version||0)+1;clearInterval(this._timer);clearInterval(this._rotate);clearInterval(this._expiry);},
 async load(){const user=wx.getStorageSync('user');if(!user||!user.id){this._items=[];this.setData({current:null});return;}const version=this._version=(this._version||0)+1;try{const r=await request('GET','/announcements',null,{silent:true});if(!this._active||version!==this._version)return;this._key='announcement-dismissed:'+user.id;this._offset=new Date(r.serverNow).getTime()-Date.now();const saved=wx.getStorageSync(this._key),dismissed=Array.isArray(saved)?saved:[];this._items=r.items.filter(x=>!dismissed.includes(x.id+':'+x.revision));if(!this._items.some(x=>x.id===this.data.current?.id&&x.revision===this.data.current?.revision))this.next();}catch(_){if(this._active){this._items=[];this.setData({current:null});}}},
 next(){clearTimeout(this._rotate);const now=Date.now()+(this._offset||0);this._items=(this._items||[]).filter(x=>new Date(x.endsAt).getTime()>now);const index=this._items.findIndex(x=>x.id===this.data.current?.id);const item=this._items[(index+1)%this._items.length]||null;const current=item?{...item,duration:Math.max(12,(item.title.length+item.content.length)/5)}:null;this.setData({current});if(current&&this._active)this._rotate=setTimeout(()=>this.next(),current.duration*1000);},
 close(){const item=this.data.current;if(!item)return;const saved=wx.getStorageSync(this._key)||[];wx.setStorageSync(this._key,[...saved,item.id+':'+item.revision].slice(-200));this._items=this._items.filter(x=>x.id!==item.id);this.next();},
 detail(){const c=this.data.current;if(c)wx.showModal({title:c.title,content:c.content,showCancel:false,confirmText:'知道了'});}
}});
